server:
  port: 9099

spring:
  application:
    name: vedio-services

  data:
    mongodb:
      host: localhost
      port: 27018
      database: vediodb

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true

info:
  app:
    name: "video-service"
    description: "This is video service"
    version: "1.0"