spring:
  application:
    name: api-gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lowerCaseServiceId: true
server:
  port: 9095


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true
  endpoint:
    gateway:
      enabled: true #gateway k end point enable ho jayenge actuator se aur hun dekh sakte h ki kon routing kr raha h

info:
  app:
    name: "Gateway-service"
    description: "This is Gateway service"
    version: "1.0"

# spring cloud gateway property--spring.cloud.gateway.discovery.locator.enabled=true-- it will provide url so we can directly access other services through this service

